server:
  port: 8080

auth:
  service:
    url: http://localhost:8081/authorizer

spring:
  application:
    name: Cars365Apg
  cloud:
    gateway:
      routes:
        - id: AuthService
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: SearchService
          uri: http://localhost:8082
          predicates:
            - Path=/search/**
          filters:
            - name: JwtValidationFilter
